language: java

install: true

env:
  global:
  - SURGE_LOGIN="danilo.pianini@gmail.com"
  - secure: "yDjIqt7To0vHTj3JEkRxNGFSrb2b9n1WD9tAgSooTDP7rR7gXJYWjnvnHxVnyFRPWGDuWLipoO8Tk645rMaLAXgv/Tp1tsrneuLnUQDnM75ovLFl5fi0F6rwcicNn9g2SVQ+j97IBOJB+6YynzpTJadHn7p7aKTWNJZPLSaEsQLk4PZ5GuPgj1AhpCQJQ6dyAiqQE2yYvlRPl+ChosCoozoLmkk3cFnL+LGqXCkIZmmRdjiiOO2yFhxVl/8gtOB2qVyzr6itBryvSN2QHWgUpgPiZIocCPvAeMMkiEWc5W40FXFLsa96r7QFnbI9X1HHVoNCAiukhX5jZw4JrwsyAHIPRNAMlYXplbKhy1EJr87wkMmMMBEl+mAtZSzbPYg1O1U4waT8Xbju4JpPlz8twZ3+yItApIcX5zCY62ZVe2RCp0jocUb26RCahZCJJjxYVc9fwA//31Hj7Xv0Nhgsriwb8oUVWiqNx3nUGVl8ymVyqLhs84GNM3BvJfqtTeO8DPCK8oq6UmRyLLydPKm4U0oTpzvdHMmdg0HuSLYhJALnUeHSzIpKQ3o9XWyMW57+igAq+CmzQHRTs8Ai9BByfkhfzB+21Fr25e2dFc9PbDxMqKqtJSnWpon03Bgq3O0lhgKcoAj5DTqoBUbGmKE1GfAjX2u9iZH4ZmBzEWio08Q="

script:
  - ./gradlew test javadoc assemble buildDashboard

deploy:
  - provider: surge
    project: build/reports/jacoco/test/html/
    domain: scm-iot-2018-coverage.surge.sh
    skip_cleanup: true
    on:
      repo: DanySK/Gradle-Wrapper
      branch: develop
