language: java

env:
  global:
   - SURGE_LOGIN=langeliandrea@gmail.com
   - secure 
   
install:
  - echo "Do nothing"

script:
  - ./gradlew clean buildDashboard  
   
deploy:
  provider: surge
  project: build/reports/
  domain: 2018-scm-reports-andrea.surge.sh