language: java

env:
  global:
   - SURGE_LOGIN=langeliandrea@gmail.com
   - secure:M0PWFFaA8ERJTX7UVtLCU1B7hTAbSqAgXPe0scQ5+OQMYDmukK6NGF2KjEl52o42wdrxKnON07iYqt5tfIHXEKTQgJzZ4tSJ/NHZxGxSLHeiyf/V1t2GP1t6GnJp1PZEBq0OGwUR8VO1YjuoK9j5CQPSpEnhSa6QsVMNW72RXJAscDxzx98JqPoc1POA5ZXnhVH7TlyZ4r1I1oMEIRQkPOOCIlwAHECR/z1XBgebyey+FtoOp+bcAftcFU3X7ELYN9MsTO0qRoh8k9jHA3Ut+LbRK6KR4w7cB++U3ZfiEC7WqIjQNUSZEHS2BQfrwRNNMClIFmYpCoYj6o+JW2JIvh2jOUMdL0qqEcuGD22hElFUwdcttLQUCTqggp00bbdbvAcVK+wJpJzLlHGs7Mdv8tGhS0ec5/BWpsU6cfSqij8Z0B2Xc/0OyeayBhi/PXygHpAf0gN/FC/1MWCOTsoeI0v3zdFlC77bw0khLSiGwJMS8FesvuEMB15vG3ra1VyLUJ0Mz6OOq8Q1ZQeZoq87xvDecJ6zjbc6BlmBBPoVBXsWuIynwDTiDdKZZ3sHL9klgqn27lPYmLFaEiqrvBTsLKFGZksMHKJMmw3X5wmHItb+W4a/0W7d9Wdtjv+s5RGtYzyqil9OviaoHii8hJIgPdwp1mPJTxTxMikJNRULT4w=


   
install:
  - echo "Do nothing"

script:
  - ./gradlew clean buildDashboard  
   
deploy:
  provider: surge
  project: build/reports/
  domain: 2018-scm-reports-andrea.surge.sh
  skip_cleanup: true
  on:
     all_branches: true